### ISSUE TITLE
Type System

### ISSUE THREAD

**Issue by igorbonadio** [positron-lang/spec#4]
Which type system should Positron use?

I suggest a static type system with type inference.

Haskell has a good one (http://en.wikipedia.org/wiki/Hindley–Milner_type_system) which we should take a look.

**Comment by renatocf** [comment]
I agree. Under the assumption that we are building a system language, I believe that types are necessary to deal with OSs common primitives (as `char`, `int` and others), which are came from their traditional C implementations.

Haskell ability to make type deduction is awesome, although I had few opportunities to test them. Taking  a superficial look in your link, Wikipedia warns:

> HM is preferably used for functional languages.

The word "preferably" seems tricky for me: to what extent use this type inference system will led us to a functional language? At this moment, we haven't discussed yet what will be the main Positron's paradigm. So maybe we should hold this question for a while, until we decide these high level behaviors of the language. I'll create an issue for that, and after this I believe we'll be able to evaluate the type system in a more concrete way.

**Comment by igorbonadio** [comment]
I read it too... But I think is not exclusive to functional languages... Rust, for example uses something like that.

**Comment by renatocf** [comment]
It's nice to know that. My knowledge about Rust is short. If it's possible to adapt HM, that's great! Further, I believe that a system suitable for a functional language could help to achieve what I see as the general paradigm of the language. Take a look at #5 and see what you think.

And, just to make it clear, I really like the idea of type inference in Positron! Not having to write types (or, at least, making it optional) will help to clear Positron's syntax - and syntax is something I consider a big issue in C and C++.

**Comment by vinivendra** [comment]
As an interesting reference, I'd like to point out [Swift's type system](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID322). It's a simple system with type inference on a procedural-oo language.
As a bonus, it has some interesting concepts that might be worth looking into, such as [**optionals**](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID330), [**dictionaries**, **functions** and **tuples**](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Types.html#//apple_ref/doc/uid/TP40014097-CH31-ID445).

**Comment by vinivendra** [comment]
I just realized Swift's documentation can be kind of hard to understand (it's really formal), so I might give a better explanation of what those features mean in the near future :) but it's a bit early for that, let's decide on the paradigm first.

**Comment by ademar111190** [comment]
I'm thinking in something close to mathematics, for example:

```
Natural  n ←  0
Integer  i ← -7
Rational r ← -1÷12
Real     r ← √-1
```

and booleans as Yes and No like Obj-c

```
Boolean  b ← Yes
```

chars and strings should be an unique thing, and remove the " or '

```
Text     c ← Abc and D!
```

but are some ideas that i want to share.

**Comment by vinivendra** [comment]
I really like the mathematics and booleans ideas.

Also, having Text as opposed to an array of `char`s might be really good. The "impossibility" of iterating over a string might force users to think more about Unicode features (such as accented characters, which are completely absent from ascii). Positron's standard library might then offer Unicode-aware ways to grab individual letters (which might be composed of multiple characters).

**Comment by renatocf** [comment]
I believe that, for our discussions in #6, we all agree that Positron has a **strong static type system**, with **automatic type deduction**.

As we're in a conceptual discussion, we can choose the type deduction algorithm (either Haskell's, Swift's or other) in another moment. So, I'm closing this Issue.

**Comment by renatocf** [comment]
Marking as opened to #18
