### ISSUE TITLE
Variable Bindings

### ISSUE THREAD

**Issue by igorbonadio** [positron-lang/spec#6]
Lets start with a basic feature: **Variable Bindings**.

How should positron's syntax be?

**Comment by igorbonadio** [comment]
@ademar111190 started it in the issue #4 and I will add some other forms:
- Scala-like syntax

``` scala
var str1 = "mutable"
val str2 = "immutable"

var x: Int = 4
val y: int = 2
```

I like this syntax because it is explicit. You know that str1 is mutable (because it is variable) and str2 is immutable (because it is a value).

Note that you can add a type, if you want. And, again, I like this syntax because it is easy to read: "variable x of type Int is equal 4".

**Comment by ademar111190** [comment]
Yesterday talking with @igorbonadio we think in a struct like this:

```
var x = 1 as Natural
val y = 3,14 as Real
val z = 7 // type automatically assigned
```

**Comment by igorbonadio** [comment]
@ademar111190 How can I declare a variable without initialize it?

**Comment by renatocf** [comment]
I liked this 2nd syntax. I think it is more readable than the Scala-like version. Answering @igorbonadio question, it seems that the natural syntax would be:

``` scala
var x as Natural;
val z as Real;
```

**Clear** and **Simple**. What makes me believe this is a good suggestion!

**Comment by igorbonadio** [comment]
Yeah. I think it is beautiful.

But I think Positron should not allow 'val' declaration without initialization.

**Comment by igorbonadio** [comment]
I was thinking if it will fit when defining methods and anonymous functions.

So I will open issues about them and link here (issue #9 and issue #10 ). I believe they are correlated.

**Comment by renatocf** [comment]
I was thinking: isn't this expression I wrote a default initialization? I mean: `x` is a variable initialized with `0` and `z` is a value initialized with `0.0`? If this is the case, OK. But I think this is not the best way.

Perhaps we should discuss how it'll be the notation for default initialization. I believe it should be uniform among all types. For example: if an object is initialized by calling its class with (), we could have:

``` scala
var x = Natural()  // Ok
val z = Real()     // Ok

var x as Natural   // Default initialization for class Natural?
val z as Real      // Default initialization for class Real?

var x              // Failure: impossible to do auto type deduction
val z              // Failure: impossible to do auto type deduction

var x = 2          // Type deducted as Natural
val z = 4.0        // Type deducted as Real
```

**Comment by igorbonadio** [comment]
I don't like the idea of default initialization... I prefer an explicit initialization...

``` scala
var x as Natural  // x is nil
val z as Real      // Error! 'val' needs an initialization

var x // syntax error
val y // syntax error
```

**Comment by renatocf** [comment]
Do you agree with the existence of class default constructor (`var x = Natural()`) and explicit (`var x = 2`) initialization?

And, as I see, you'd like Positron to have a `nil` singleton object to be the default "not initialized" value. But I believe it says much more than that. Will variables and values be implicit pointers/references to objects? And to that, will objects be initialized in the heap? I believe both assumptions would harm performance (3rd Law). And if it's not the case, what's gonna be the type deduced to `x` in your example?

I don't know if this constructions are present in other languages, and the questions I made can be simply answered. If that's true, how other compiled languages deal with that?

**Comment by vinivendra** [comment]
I talked to @renatocf about this, and personally I'm not a fan of putting types at the end. I think it might make things unnecessarily hard if we have longer assignments:

```
var someVarName = theResultOfAFunctionThatTakesSomeArguments(functionWithALongName(),
                                      functionWithSomeOtherLongName()) as Natural
```

I like the scala way better. Also, I'd suggest switching `val` for `let`, just because it's easier to tell `var`and `let` apart when they're in the middle of other code.

I'd suggest some alternatives:

```
// Implied types:
var str1 = "mutable"
let str2 = "immutable"

// Alternatives:
var x: Real = 2
var x as Real = 2
var Real x = 2
var x in Real = 2
var x ∈ Real = 2
```

Personally, I prefer the first and last forms, though the last one does involve some unicode :/

**Comment by igorbonadio** [comment]
@renatocf, I dont know if I like default constructor (like in c++)... Maybe we should force a single constructor... And if you need a diferente constructor, you should provide 'static methods' that return new instances. I think is a little bit clear that c++/java's style.

And I'm not sure about nil... I will think more about it...

Now about heap and stack... If we will treat all as object, I believe the easiest way is to set all variables as references to something... There are alternatives... you can see Rust, for example.

**Comment by igorbonadio** [comment]
Yes... @vinivendra has a good point. Types at the end are difficult to read.

And again, var and val are very similar... so I agree with you suggestion to change val to let.

**Comment by igorbonadio** [comment]
So, I prefere:

``` scala
var str1 = "mutable"
let str2 = "immutable"

var x: Int = 2
let y: Int = 3
```

**Comment by igorbonadio** [comment]
And I think we should support unicode (UTF-8) source code. But the core language should not use unicode characters.

**Comment by ademar111190** [comment]
I'm not a fan of `null` I prefer a default value for null safety.
I liked `let` suggestion.
About types at end, I think it is not a problem, normally you do not declare the type, it will be implicit, for example:

```
var someVarName = theResultOfAFunctionThatTakesSomeArguments(functionWithALongName(),
                                  functionWithSomeOtherLongName()) as Natural
```

should be:

```
var someVarName = theResultOfAFunctionThatTakesSomeArguments(functionWithALongName(),
                                  functionWithSomeOtherLongName())
```

because the `theResultOfAFunctionThatTakesSomeArguments` already have a return type declared.

A good point for types at the end is the readability.

**Comment by renatocf** [comment]
Well, I'd recommend for someone who wrote code like this to apply the [Extract Variable](http://www.refactoring.com/catalog/extractVariable.html) and [Rename Method](http://www.refactoring.com/catalog/renameMethod.html) refactorings. I don't want Positron's users to write in a C-like style (with functions as `atoi`), but I also don't want the Java way (`aVariableWithAVeryLongAndDifficultToReadCamelStyleName`).

My point here is: **we should not base our design on bad programming practices**. Even the most beautiful language will be ugly when written in an unreasonable way... I think it's fair to expect someone writing a less ugly (not necessarily more beautiful - which is impossible sometimes):

``` scala
let result1 = functionWithALongName()
let result2 = functionWithSomeOtherLongName()

var someVarName as Natural;
someVarName = theResultOfAFunctionThatTakesSomeArguments(result1, result2)
```

Based on that, I came out with an alternative notation:

``` scala
var sum in Natural : sum = 2 + 2
```

would get close to the mathematical reading:

> Sum is a variable in Naturals, such that sum is equal to 2+2

In this way, the type-only, attribution-only and type-and-attribute bindings would be:

``` scala
var x in Natural
var y = 2 + 2
var z in Natural : z = 42
```

Note that although I introduced the `:` as part of the notation, it's the same as writing:

``` scala
var z in Natural
z = 42
```

Same set of rules for `let` and values.

**Comment by vinivendra** [comment]
My previous comment showed up late because of technical difficulties, but that's ok.

@renatocf makes a good point: we should not base our design on bad programming practices. That makes a strong case for types at the end. Personally, I prefer `as` over `in`; I think `in` makes more sense when thinking about sets (such as `Natural`s) but not so much with actual objects, such as `x in SceneManager` or something like that.

Also, I think the `var z in Natural : z = 42` notation has great value for the mathematical resemblance, but I don't like repeating the variable name. Longer names, especially, might make it unnecessarily unclear. I would prefer:

``` scala
var x as Natural
var y = 2 + 2
var z as Natural = 42
```

I was gonna get a lot off-topic and start talking about initializations, nil, null, etc, but I'm gonna leave that to [#11](https://github.com/positron-lang/spec/issues/11). I think we can assume for now that we will allow variables to not be initialized, just for the sake of discussing the syntax.

**Comment by vinivendra** [comment]
Sorry, I forgot about types at the end. I believe I do prefer them:

``` scala
var x as Natural
var y = 2 + 2
var z = 42 as Natural
```

**Comment by vinivendra** [comment]
Also, someone mentioned this:

``` scala
var x
```

I like it, in the sense that we would have an `Any` type, something kind of like a `void *`. Then again, maybe this would be better:

``` scala
var x as Any
```

However, pattern matching and polymorphism are good alternatives for an `Any` type.

**Comment by igorbonadio** [comment]
Wow! There are so many comments here! It's really good!

@renatocf I dont like the 'var sum in Natural : sum = 2 + 2' notation... It is so redundant...

The notation 'var z = 42 as Natural' seems good, but I think it will not fit methods/function declaration.

And I though about nil values, and I agree with @vinivendra . Maybe an 'Any' type could be a good solution.

**Comment by igorbonadio** [comment]
Ah, and I still prefer the scala-like syntax:

``` scala
var str1 = "mutable"
let str2 = "immutable"

var x: Int = 2
let y: Int = 3
```

**Comment by renatocf** [comment]
I agree. The notation I purposed has too much repetition. Thinking about this topic, I realized that if languages never adopted a purely mathematical notation, it's probably because it's difficult to fit this notation in the rest of the language.

Now, about the notation, I'm still undecided...

So far, we got 3 major options:
1. `var x = 2 as Natural`, which we can read "variable x initialized with 2 as a Natural". 
2. `var x : Natural = 2`, which can be read as "variable x of type Natural initialized with 2"
3. `var x as Natural = 2`, a mixed version that means "variable x as Natural equals 2"

Before we get to a decision, I'd like we consider how it's gonna be the initialization for user-defined types. First of all, let's suppose we have a class `Point`, whose constructor has 2 parameters, `x` and `y`. So we would have:

``` scala
// 1st style
var x as Point
var y = Point(1,1)
var z = Point(1,1) as Point

// 2nd style
var x : Point
var y = Point(1,1)
var z : Point = Point(1,1)

// 3rd style
var x as Point
var y = Point(1,1)
var z as Point = Point(1,1)
```

That's it?  Considering my view of how objects of user-defined classes are constructed, the third binding (declaration + definition) seems strange in all styles purposed. Although we avoid replication in variable names, we get replication in types.

Wouldn't be easier if we collapsed them in an uniform style?

``` scala
// 1st style
var x = Point()
var y = Point(1,1)

// 2nd style
var x : Point()
var y : Point(1,1)

// 3rd style
var x as Point()
var y as Point(1,1)
```

In this context, I think the 1st style is the best. If we follow the rule "everything is an object" (as discussed in Issue #5), it can be enough to solve the problems with numbers:

``` scala
var x = 1          // Raw number, deduced as `Natural` or `Integer`
var y = Real(1)    // Force raw number `1` to be `Real`, using `Real` class constructor
var z = 1.0        // Raw number with decimal, deduced as `Real`
var w = Natural()  // Default value for `Natural` type: `0`
```

I think this notation is **clear**, **simple** and **standardized**.

**Comment by igorbonadio** [comment]
@renatocf I dont think we should use ('as' | ':') Point(1, 1)... because Point(1, 1) is not a type.

I think it should be

``` scala
// 1st style
var x = Point()
var y = Point(1,1)

// 2nd style
var x = Point()
var y = Point(1,1)

// 3rd style
var x = Point()
var y = Point(1,1)
```

The type should be used only when the programmer want to improve readability (or when it should be initialized with nil).

And again, I dont like default constructors... it is not clear:

``` scala
var w = Natural()
```

But it is:

``` scala
var w = Natural(0)
```

**Comment by vinivendra** [comment]
I think constructors that take no arguments may be fitting to some classes, but they don't necessarily have to be the default ones. Also, they don't have to be available for all classes, sometimes they don't make sense.

I think it's important that we remember that types are inferred here. Because of that, I do think

``` scala
var x = Point()
var y = Point(1,1)
```

is the way to go for user defined types - it's already pretty clear what type will be returned.

Now, what if we treated the `as` notation like a type cast? That way, we'd have:

``` scala
var x = 3               // The default language type, i.e. Integer
var y = 3.2             // Some other default type, i.e. Real
var z = 3.2 as Rational // Initially a Real, but cast to Rational
var w as Integer        // Initially an Any, but 'cast' to an Integer
```

That way, we basically let inferred typing do its thing for us.

**Comment by igorbonadio** [comment]
I'm not against constructors that takes no arguments. I just dont like multiple constructors...

For example, imagine an object that configures something:

``` ruby
config = Config.new
config.property1 = "blah"
config.property2 = "blah"
config.property3 = "blah"
```

And imagine you can get those configs from YAML files:

``` ruby
config = Config.new("configs.yml") # multiple constructor
config = Config.fromYML("configs.yml") # Single constructor version. fromYML is a static method
```

I prefer the last one.

**Comment by igorbonadio** [comment]
@vinivendra I agree! I liked you idea. `as` should be a type cast, and then we can let the compiler infers the type.

But it doesn't solve our problem of type annotation... I still prefer the scala-like syntax (with `let`).

**Comment by igorbonadio** [comment]
Sorry... "But it does solve our problem of type annotation" should be "But it doesn't solve our problem of type annotation".

I fixed in my last comment...

**Comment by renatocf** [comment]
I think the cast style with `as` is very **clear**, so I believe we can use it.

Now, about the `:`. At first it's not my favorite stype, but I think it may be useful in other features we'll discuss, as functions. A function declaration with explicit types like this:

``` scala
// Funcion and lambda syntaxes are topic for other issues...
def exterminate(Doctor : Gallifreyan, Companion : Human)
```

is very beautiful. So, if we choose a binding:

``` scala
let x : Real = 0
```

we get a language more **standardized** - in compliance with the 2nd Law.

**Comment by igorbonadio** [comment]
I agree

**Comment by renatocf** [comment]
So, in short, I agree with this style:

``` scala
var ramanujan = 1729 // mutable objects
let theAnswer = 42   // immutable objects

var x0               // Type Any, value `nil`
var x1 : Real        // Type Real, value `nil`
var x2 = 42          // Type deducted from literal expression
var x3 = Real(42)    // Type deducted from class constructor
var x4 : Real = 42   // Explicit type declaration
var x5 = 42 as Real  // Type cast - valid **only** within this expression

let y0               // Error! Constants have to be initialized!
let y1 : Real        // Error! Constants have to be initialized!
let y2 = 42          // Type deducted from literal expression
let y3 = Real(42)    // Type deducted from class constructor
let y4 : Real = 42   // Explicit type declaration
let y5 = 42 as Real  // Type cast - valid **only** within this expression
```

What do you think? The last expression (with `y5`) is a guess - I'm not very sure what we should do in that case. But how about the others? Do they seem ok?

**Comment by igorbonadio** [comment]
I agree with all expressions except the 3rd.

I think it is better to explicitly declare the Any type:

``` scala
var x0       // syntax error!
var x1 : Any // Ok
```

**Comment by renatocf** [comment]
No preferences about this. In this way, we'll enforce a user to either declare the type (initialized with `nil`) or define its value/variable.

**Comment by vinivendra** [comment]
I agree about types - I'd rather the user always be clear about the type he wants, even in Any's - but I disagree about the notation.

Personally, I really dislike the way functions are declared and called in most languages, so I think we shouldn't bring that into this discussion.

With that in mind, I would defend a more standardized approach. No need to use ':' if we can always use 'as', or the other way around. Also, no need to add "var x as Real = 42" if we can do "var x = 42 as Real" and get the same result.

Personally I prefer 'as' over ':', but that's not really the point I want to make. I would explain this better, but I'm on a cellphone right now :/

**Comment by renatocf** [comment]
As @vinivendra can't write, I think his proposal is:

``` scala
var ramanujan = 1729 // mutable objects
let theAnswer = 42   // immutable objects

var x0               // Error! No type declared!
var x1 as Real       // Type Real, value `nil`
var x2 = 42          // Type deducted from literal expression
var x3 = Real(42)    // Type deducted from class constructor
var x4 = 42 as Real  // Explicit type declaration

let y0               // Error! No type declared!
let x1 as Real       // Type Real, value `nil`
let y2 = 42          // Type deducted from literal expression
let y3 = Real(42)    // Type deducted from class constructor
let y4 = 42 as Real  // Explicit type declaration
```

And in this way, a type cast would be:

``` scala
y2 as Real // cast, valid within this expression
```

@vinivendra has a point, as it's still **clear** and **simple**, but more standardized.

For me, both styles are OK. You can argue for and against the use of `:`.

**Comment by vinivendra** [comment]
That's exactly it, thanks for the help!

Just a philosophical correction: to me, "var x = 42 as Real" is a type cast and then a type inference, not an explicit type declaration per se. Not that there's much of a difference.

**Comment by renatocf** [comment]
> A type cast and then a type inference

This implies that as we read `42` we deduce it as an integer. Casts, with a high priority (perhaps the highest) applies, and we get a `Real` type in the right side side of the attribution. Finally, `x4` type is deducted with from the same right side of the expression.

Just commenting to make it clear for myself.

**Comment by vinivendra** [comment]
Yeah, that's what I had in mind. Maybe not that implementation behind the curtains, but that way of thinking.

**Comment by igorbonadio** [comment]
I think the first proposal (with `:`) is better. I will try to show some points:
- the `as` keyword has just one meaning: cast
- `:` is used to declare the variable type
- I think it is more uniform (and less ambiguous) than the 2nd alternative, which `as` has 2 meanings (cast and declare variable type)
- I think it will fit very well in function definitions. (we can discuss about it in other issues [issue #10 e #9 ] to help close this one)

**Comment by igorbonadio** [comment]
Let's close this issue?

We can use `as` or `:`. But I think `:` is better (as I said in the last comment). And we can use `as` to cast.

What do you think?

**Comment by ademar111190** [comment]
I agree, I prefer the `:` too. and `as` is perfect for cast.

**Comment by vinivendra** [comment]
Sure! Can you formalize your proposal, just so everyone can approve it?

**Comment by igorbonadio** [comment]
I have 2 proposals:

_obs: the following grammars are just examples... they may change_

## Cast

Users can cast expressions using `as`.
-  Grammar

``` antlr
expression : cast
           ; // and more...

cast : expression 'as' ID
     ;
```
- Examples:

``` scala
42 as Real // evaluates to 42.0
```

## Variable Binding

There are 2 kinds of bindings: immutable (`let`) and mutable (`var`). Users can explicitly specify types or let the compiler infers them. Note that just mutable variables could be defined without an initial value (it will be nil by default).

Variable binding is an expression which evaluates to its value.
- Grammar:

``` antlr
expression : binding
           ; // and more...

binding : var_binding
        | let_binding
        ;

var_binding : 'var' ID type
            | 'var' ID type? '=' expression
            ;

let_binding : 'let' ID type? '=' expression
            ;

type : ':' ID
     ;
```
- Examples:

``` scala
var ramanujan = 1729 // mutable objects
let theAnswer = 42   // immutable objects

var x0               // Error! No type declared!
var x1: Real         // Type Real, value `nil`
var x2 = 42          // Type deducted from expression (literal)
var x4 = 42 as Real  // Type deducted from expression (cast)

let y0               // Error! No type declared!
let x1: Real         // Error! No type declared!
let y2 = 42          // Type deducted from expression (literal)
let y4 = 42 as Real  // Type deducted from expression (cast)
```

**Comment by igorbonadio** [comment]
I forgot to write the `type` rule... The last comment was updated.

**Comment by vinivendra** [comment]
Alright! That's great, though it's a lot more formal than I expected. I approve!

**Comment by ademar111190** [comment]
Just a doubt about `nil` we're thinking Positron will have only objects instances or Positron will have primitives types too?

```
var α: Real  // OK type Real value nil
var β: real  // primitive types???
```

**Comment by igorbonadio** [comment]
Everything will be an object. We can optimize some values, like numbers. But the user will treat all as objects

**Comment by vinivendra** [comment]
I agree: we should probably treat these as primitives, though to the user they will all be objects.

**Comment by igorbonadio** [comment]
Can I close this issue?

**Comment by renatocf** [comment]
I think we have agreed in the main points of this issue:
- the grammar (as @igorbonadio proposed comments above)
- the principles (everything is like an object, with primitive types (that exist for efficiency) are hidden from users under an object interface)

**Comment by renatocf** [comment]
Marking as opened to #18
